reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T03:12:10.959Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:36627 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:36627
2020-07-24T03:12:11.086Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36627 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627
2020-07-24T03:12:11.302Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36627 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:12:10.959Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:36627 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:36627
2020-07-24T03:12:11.086Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36627 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627
2020-07-24T03:12:11.302Z, RpcRetryingCaller{globalStartTime=1595560330212, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36627 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36627 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36627
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T03:17:35.141Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
2020-07-24T03:17:35.260Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
2020-07-24T03:17:35.476Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:17:35.141Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
2020-07-24T03:17:35.260Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
2020-07-24T03:17:35.476Z, RpcRetryingCaller{globalStartTime=1595560654431, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41003 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41003
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is -1

Test vvMode=v2v2
tr.result is 1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.129Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:02.815Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:02.918Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.123Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553

2020-07-24T03:36:03.542Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.232Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.337Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.541Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553

2020-07-24T03:36:04.061Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.747Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.851Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:04.059Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:41553 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:41553


stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.129Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:02.815Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:02.918Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.123Z, RpcRetryingCaller{globalStartTime=1595561762812, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553

2020-07-24T03:36:03.542Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.232Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.337Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.541Z, RpcRetryingCaller{globalStartTime=1595561763229, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553

2020-07-24T03:36:04.061Z, RpcRetryingCaller{globalStartTime=1595561760758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.747Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.851Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:04.059Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:41553 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:41553


	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:36:03.747Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:03.851Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:41553 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:41553
2020-07-24T03:36:04.059Z, RpcRetryingCaller{globalStartTime=1595561763744, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:41553 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:41553

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.MetaTableAccessor.getTableState(MetaTableAccessor.java:1118)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getTableState(ConnectionImplementation.java:2039)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.isTableDisabled(ConnectionImplementation.java:630)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:219)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:105)
	... 27 more
Caused by: java.net.ConnectException: Call to f7368fae304e/172.17.0.15:41553 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:41553
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:304)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1426)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:924)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:41553
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T03:44:18.565Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:43471 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:43471
2020-07-24T03:44:18.688Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43471 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471
2020-07-24T03:44:18.906Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43471 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:44:18.565Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:43471 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:43471
2020-07-24T03:44:18.688Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43471 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471
2020-07-24T03:44:18.906Z, RpcRetryingCaller{globalStartTime=1595562257863, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43471 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43471 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43471
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is -1

Test vvMode=v2v2
tr.result is 1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T03:51:15.011Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
2020-07-24T03:51:15.158Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
2020-07-24T03:51:15.401Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T03:51:15.011Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
2020-07-24T03:51:15.158Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
2020-07-24T03:51:15.401Z, RpcRetryingCaller{globalStartTime=1595562673831, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43052 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43052
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is -1

Test vvMode=v2v2
tr.result is 1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T04:39:39.573Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40165 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40165
2020-07-24T04:39:39.701Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40165 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165
2020-07-24T04:39:39.924Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40165 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T04:39:39.573Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40165 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40165
2020-07-24T04:39:39.701Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40165 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165
2020-07-24T04:39:39.924Z, RpcRetryingCaller{globalStartTime=1595565579090, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40165 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40165 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40165
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T04:53:57.577Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:35979 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:35979
2020-07-24T04:53:57.715Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:35979 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979
2020-07-24T04:53:57.931Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:35979 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T04:53:57.577Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:35979 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:35979
2020-07-24T04:53:57.715Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:35979 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979
2020-07-24T04:53:57.931Z, RpcRetryingCaller{globalStartTime=1595566436770, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:35979 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:35979 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:35979
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is -1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T05:19:20.196Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:44522 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:44522
2020-07-24T05:19:20.331Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:44522 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522
2020-07-24T05:19:20.546Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:44522 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T05:19:20.196Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:44522 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:44522
2020-07-24T05:19:20.331Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:44522 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522
2020-07-24T05:19:20.546Z, RpcRetryingCaller{globalStartTime=1595567957965, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:44522 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:44522 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:44522
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T06:12:59.693Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:45869 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:45869
2020-07-24T06:12:59.826Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:45869 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869
2020-07-24T06:13:00.047Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:45869 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T06:12:59.693Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:45869 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:45869
2020-07-24T06:12:59.826Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:45869 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869
2020-07-24T06:13:00.047Z, RpcRetryingCaller{globalStartTime=1595571178758, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:45869 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:45869 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:45869
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is -1

Test vvMode=v2v2
tr.result is 1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T06:30:35.810Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:37862 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:37862
2020-07-24T06:30:35.962Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:37862 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862
2020-07-24T06:30:36.181Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:37862 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T06:30:35.810Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:37862 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:37862
2020-07-24T06:30:35.962Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:37862 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862
2020-07-24T06:30:36.181Z, RpcRetryingCaller{globalStartTime=1595572234884, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:37862 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:37862 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:37862
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is -1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T06:54:17.960Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:36796 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:36796
2020-07-24T06:54:18.077Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36796 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796
2020-07-24T06:54:18.287Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36796 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T06:54:17.960Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:36796 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:36796
2020-07-24T06:54:18.077Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36796 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796
2020-07-24T06:54:18.287Z, RpcRetryingCaller{globalStartTime=1595573657028, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36796 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:36796 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:36796
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T07:02:09.608Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:42244 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:42244
2020-07-24T07:02:09.743Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:42244 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244
2020-07-24T07:02:09.978Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:42244 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T07:02:09.608Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:42244 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:42244
2020-07-24T07:02:09.743Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:42244 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244
2020-07-24T07:02:09.978Z, RpcRetryingCaller{globalStartTime=1595574127786, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:42244 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:42244 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:42244
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is -1

Test vvMode=v2v2
tr.result is 1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T07:03:50.418Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
2020-07-24T07:03:50.535Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
2020-07-24T07:03:50.751Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T07:03:50.418Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
2020-07-24T07:03:50.535Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
2020-07-24T07:03:50.751Z, RpcRetryingCaller{globalStartTime=1595574229089, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:43541 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:43541
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T07:18:31.337Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:32935 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:32935
2020-07-24T07:18:31.451Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:32935 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935
2020-07-24T07:18:31.665Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:32935 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T07:18:31.337Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:32935 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:32935
2020-07-24T07:18:31.451Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:32935 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935
2020-07-24T07:18:31.665Z, RpcRetryingCaller{globalStartTime=1595575110293, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:32935 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:32935 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:32935
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is -1
v1v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T07:24:22.673Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40241 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40241
2020-07-24T07:24:22.810Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40241 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241
2020-07-24T07:24:23.032Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40241 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T07:24:22.673Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40241 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40241
2020-07-24T07:24:22.810Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40241 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241
2020-07-24T07:24:23.032Z, RpcRetryingCaller{globalStartTime=1595575462162, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40241 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40241 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40241
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more



Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is -1
v1v1 or v2v2 test failed !!!
reconf_parameter: ipc.ping.interval
component: hdfs:DataNode
v1: 60000
v2: 1000
testProject: hbase
unitTest: org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=3, exceptions:
2020-07-24T07:38:43.050Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40503 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40503
2020-07-24T07:38:43.186Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40503 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503
2020-07-24T07:38:43.416Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40503 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:
2020-07-24T07:38:43.050Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, java.net.ConnectException: Call to f7368fae304e/172.17.0.15:40503 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: f7368fae304e/172.17.0.15:40503
2020-07-24T07:38:43.186Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40503 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503
2020-07-24T07:38:43.416Z, RpcRetryingCaller{globalStartTime=1595576322352, pause=100, maxAttempts=3}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40503 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:384)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:358)
	at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: Call to f7368fae304e/172.17.0.15:40503 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:220)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:436)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:330)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$200(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:585)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:42786)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.doGet(ClientServiceCallable.java:50)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:379)
	at org.apache.hadoop.hbase.client.HTable$1.rpcCall(HTable.java:374)
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:127)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	... 27 more
Caused by: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: f7368fae304e/172.17.0.15:40503
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.getConnection(AbstractRpcClient.java:354)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callMethod(AbstractRpcClient.java:433)
	... 36 more


v1v2 failed with probability 8 out of 50
v1v1v2v2 failed with probability 8 out of 50
result: false positive !!!
Total execution time in seconds : 16107
